use crate::adapters::claude::ClaudeAdapter;
use crate::adapters::ToolAdapter;
use crate::core::event::{EventLogger, EventType, ForgeEvent};
use crate::core::state::{StateManager, TaskSummary};
use crate::core::task::{AgentType, TaskManager, TaskStatus};
use colored::Colorize;
use std::path::Path;

pub fn execute(project_root: &Path) -> anyhow::Result<()> {
    let forge_dir = project_root.join(".forge");

    if !forge_dir.exists() {
        println!(
            "{} Forge is not initialized. Run {} first.",
            "!".yellow(),
            "forge init".cyan()
        );
        return Ok(());
    }

    println!("{}", "FORGE — Sync & Reconcile".bold());
    println!("{}", "=".repeat(40));
    println!();

    let task_mgr = TaskManager::new(&forge_dir);
    let state_mgr = StateManager::new(&forge_dir);
    let event_logger = EventLogger::new(&forge_dir);

    let tasks = task_mgr.list_tasks()?;
    let state = state_mgr.load()?;

    // Step 1: Reconcile task summary
    println!("  {} Reconciling task summary...", "→".cyan());
    let mut summary = TaskSummary::default();
    summary.total = tasks.len();

    let completed_ids: Vec<String> = tasks
        .iter()
        .filter(|t| t.status == TaskStatus::Completed)
        .map(|t| t.id.clone())
        .collect();

    for task in &tasks {
        match task.status {
            TaskStatus::Pending => {
                if task.is_blocked(&completed_ids) {
                    summary.blocked += 1;
                } else {
                    summary.pending += 1;
                }
            }
            TaskStatus::Blocked => summary.blocked += 1,
            TaskStatus::Assigned | TaskStatus::InProgress => summary.in_progress += 1,
            TaskStatus::Completed => summary.completed += 1,
            TaskStatus::Failed => summary.failed += 1,
        }
    }

    state_mgr.update_task_summary(summary.clone())?;
    println!(
        "  {} Summary: {} total, {} pending, {} active, {} done, {} blocked",
        "✓".green(),
        summary.total,
        summary.pending,
        summary.in_progress,
        summary.completed,
        summary.blocked
    );

    // Step 2: Render adapter configs for each detected tool
    println!("  {} Rendering adapter configs...", "→".cyan());
    let updated_state = state_mgr.load()?;

    for tool in &state.tools {
        if !tool.available {
            continue;
        }
        match tool.agent_type {
            AgentType::Claude => {
                let adapter = ClaudeAdapter;
                adapter.render_config(&updated_state, &tasks, project_root)?;
                println!("    {} CLAUDE.md updated", "✓".green());
            }
            AgentType::Codex => {
                // Codex adapter: generate AGENTS.md
                render_codex_config(&updated_state, &tasks, project_root)?;
                println!("    {} AGENTS.md updated", "✓".green());
            }
            AgentType::Gemini => {
                // Gemini adapter: generate GEMINI.md
                render_gemini_config(&updated_state, &tasks, project_root)?;
                println!("    {} GEMINI.md updated", "✓".green());
            }
            AgentType::Any => {}
        }
    }

    // Step 3: Log reconciliation event
    event_logger.log(&ForgeEvent::new(
        EventType::StateReconciled,
        format!(
            "State reconciled: {} tasks ({} done, {} pending)",
            summary.total, summary.completed, summary.pending
        ),
    ))?;

    println!();
    println!("{} Sync complete.", "✓".green().bold());

    Ok(())
}

fn render_codex_config(
    state: &crate::core::state::ForgeState,
    tasks: &[crate::core::task::Task],
    project_root: &Path,
) -> anyhow::Result<()> {
    let assigned: Vec<_> = tasks
        .iter()
        .filter(|t| t.assigned_to.as_ref().is_some_and(|a| *a == AgentType::Codex))
        .collect();

    let mut content = String::new();
    content.push_str("# AGENTS.md (Auto-generated by Forge Orchestrator)\n\n");
    content.push_str(&format!("**Project:** {}\n", state.project_name));
    content.push_str(&format!(
        "**Last updated:** {}\n\n",
        state.updated_at.format("%Y-%m-%d %H:%M UTC")
    ));
    content.push_str("---\n\n");

    if assigned.is_empty() {
        content.push_str("## Status\n\nNo tasks currently assigned to Codex.\n\n");
    } else {
        content.push_str("## Assigned Tasks\n\n");
        for task in &assigned {
            content.push_str(&format!("### {}: {}\n\n{}\n\n", task.id, task.title, task.description));
            if !task.acceptance_criteria.is_empty() {
                content.push_str("**Acceptance Criteria:**\n");
                for c in &task.acceptance_criteria {
                    content.push_str(&format!("- [ ] {c}\n"));
                }
                content.push_str("\n");
            }
        }
    }

    content.push_str("## Rules\n\n");
    content.push_str("- Complete tasks one at a time\n");
    content.push_str("- Do NOT modify files outside your assigned task scope\n");
    content.push_str("- Run tests before marking a task complete\n");

    std::fs::write(project_root.join("AGENTS.md"), content)?;
    Ok(())
}

fn render_gemini_config(
    state: &crate::core::state::ForgeState,
    tasks: &[crate::core::task::Task],
    project_root: &Path,
) -> anyhow::Result<()> {
    let assigned: Vec<_> = tasks
        .iter()
        .filter(|t| t.assigned_to.as_ref().is_some_and(|a| *a == AgentType::Gemini))
        .collect();

    let mut content = String::new();
    content.push_str("# GEMINI.md (Auto-generated by Forge Orchestrator)\n\n");
    content.push_str(&format!("**Project:** {}\n", state.project_name));
    content.push_str(&format!(
        "**Last updated:** {}\n\n",
        state.updated_at.format("%Y-%m-%d %H:%M UTC")
    ));
    content.push_str("---\n\n");

    if assigned.is_empty() {
        content.push_str("## Status\n\nNo tasks currently assigned to Gemini.\n\n");
    } else {
        content.push_str("## Assigned Tasks\n\n");
        for task in &assigned {
            content.push_str(&format!("### {}: {}\n\n{}\n\n", task.id, task.title, task.description));
            if !task.acceptance_criteria.is_empty() {
                content.push_str("**Acceptance Criteria:**\n");
                for c in &task.acceptance_criteria {
                    content.push_str(&format!("- [ ] {c}\n"));
                }
                content.push_str("\n");
            }
        }
    }

    content.push_str("## Guidelines\n\n");
    content.push_str("- Complete tasks one at a time\n");
    content.push_str("- Do NOT modify files outside your assigned task scope\n");
    content.push_str("- Run tests before marking a task complete\n");

    std::fs::write(project_root.join("GEMINI.md"), content)?;
    Ok(())
}
