use super::ToolAdapter;
use crate::core::state::ForgeState;
use crate::core::task::Task;
use std::path::Path;
use std::process::Command;

pub struct ClaudeAdapter;

impl ToolAdapter for ClaudeAdapter {
    fn name(&self) -> &str {
        "claude"
    }

    fn render_config(
        &self,
        state: &ForgeState,
        tasks: &[Task],
        project_root: &Path,
    ) -> anyhow::Result<()> {
        let assigned_tasks: Vec<&Task> = tasks
            .iter()
            .filter(|t| {
                t.assigned_to
                    .as_ref()
                    .is_some_and(|a| *a == crate::core::task::AgentType::Claude)
            })
            .collect();

        let mut content = String::new();
        content.push_str("# CLAUDE.md (Auto-generated by Forge Orchestrator)\n\n");
        content.push_str(&format!("**Project:** {}\n", state.project_name));
        content.push_str(&format!(
            "**Last updated:** {}\n\n",
            state.updated_at.format("%Y-%m-%d %H:%M UTC")
        ));
        content.push_str("---\n\n");

        // Current task assignments
        if assigned_tasks.is_empty() {
            content.push_str("## Status\n\nNo tasks currently assigned to Claude.\n\n");
        } else {
            content.push_str("## Assigned Tasks\n\n");
            for task in &assigned_tasks {
                content.push_str(&format!(
                    "### {}: {}\n\n{}\n\n",
                    task.id, task.title, task.description
                ));
                if !task.acceptance_criteria.is_empty() {
                    content.push_str("**Acceptance Criteria:**\n");
                    for criterion in &task.acceptance_criteria {
                        content.push_str(&format!("- [ ] {criterion}\n"));
                    }
                    content.push('\n');
                }
                if !task.locked_files.is_empty() {
                    content.push_str("**Files you may modify:**\n");
                    for file in &task.locked_files {
                        content.push_str(&format!("- `{file}`\n"));
                    }
                    content.push('\n');
                }
            }
        }

        // Governance rules
        content.push_str("## Governance\n\n");
        content.push_str("- Report task completion via MCP: `forge_complete_task()`\n");
        content.push_str("- Do NOT modify files outside your locked file list\n");
        content.push_str("- Run tests before marking task complete\n");
        content.push_str("- Check `.forge/state.json` for current orchestration state\n\n");

        let claude_md_path = project_root.join("CLAUDE.md");
        std::fs::write(claude_md_path, content)?;
        Ok(())
    }

    fn build_command(
        &self,
        task: &Task,
        project_root: &Path,
        auth_mode: &str,
        permissions: &str,
    ) -> Command {
        let task_type = task.task_type.as_deref().unwrap_or("");

        // Build task-type-aware prompt
        let prompt = build_prompt(task, task_type);

        let mut cmd = Command::new("claude");
        cmd.args(["-p", &prompt, "--output-format", "stream-json", "--verbose"])
            .current_dir(project_root);

        // Smart permissions: scoped --allowedTools instead of blunt --dangerously-skip-permissions
        if permissions == "yolo" {
            match task_type {
                "implement" => {
                    cmd.args(["--allowedTools", "Write,Edit,Read,Glob,Grep,Bash"]);
                }
                "review" | "test" => {
                    cmd.args(["--allowedTools", "Read,Glob,Grep,Bash"]);
                }
                "document" => {
                    cmd.args(["--allowedTools", "Write,Edit,Read,Glob,Grep"]);
                }
                // design + unknown: full autonomy (may need any tool)
                _ => {
                    cmd.args(["--dangerously-skip-permissions"]);
                }
            }
        }

        // Task-type-aware turn limits
        match task_type {
            "review" | "test" => {
                cmd.args(["--max-turns", "20"]);
            }
            "design" => {
                cmd.args(["--max-turns", "30"]);
            }
            _ => {}
        }

        if auth_mode == "subscription" {
            cmd.env_remove("ANTHROPIC_API_KEY");
        }

        cmd
    }

    /// Interactive PTY mode: launch `claude` (full TUI) instead of `claude -p`.
    /// The prompt is typed into the TUI via initial_input() after startup.
    fn build_command_interactive(
        &self,
        _task: &Task,
        project_root: &Path,
        auth_mode: &str,
        permissions: &str,
    ) -> Command {
        let mut cmd = Command::new("claude");
        // No -p flag — launches full interactive TUI
        // No --output-format, no --verbose
        if permissions == "yolo" {
            cmd.arg("--dangerously-skip-permissions");
        }
        cmd.current_dir(project_root);

        if auth_mode == "subscription" {
            cmd.env_remove("ANTHROPIC_API_KEY");
        }

        cmd
    }

    /// Provide the task prompt to be typed into the Claude TUI after it initializes.
    /// Newlines are flattened to spaces — raw \n in a PTY can trigger premature
    /// submission or put Claude's TUI into multi-line mode where \r adds a line
    /// instead of submitting.
    fn initial_input(&self, task: &Task) -> Option<String> {
        let task_type = task.task_type.as_deref().unwrap_or("");
        let prompt = build_prompt(task, task_type).replace('\n', " ");
        // \r = Enter to submit the prompt
        Some(format!("{}\r", prompt))
    }

    /// Claude Code TUI shows "shift+tab to cycle" in the permission indicator
    /// at the bottom when ready for input.
    fn ready_pattern(&self) -> Option<&str> {
        Some("to cycle")
    }
}

/// Build a task-type-aware prompt for Claude.
fn build_prompt(task: &Task, task_type: &str) -> String {
    let criteria = if task.acceptance_criteria.is_empty() {
        String::new()
    } else {
        format!(
            "Acceptance criteria:\n{}\n\n",
            task.acceptance_criteria
                .iter()
                .map(|c| format!("- {c}"))
                .collect::<Vec<_>>()
                .join("\n")
        )
    };

    let files = if task.locked_files.is_empty() {
        String::new()
    } else {
        format!(
            "Files in scope:\n{}\n\n",
            task.locked_files
                .iter()
                .map(|f| format!("- {f}"))
                .collect::<Vec<_>>()
                .join("\n")
        )
    };

    match task_type {
        "design" => format!(
            "You are working on task {id}: {title}\n\n\
             This is a DESIGN task. Focus on architecture and system design.\n\n\
             Description: {desc}\n\n\
             {criteria}{files}\
             Think through the design carefully. Consider trade-offs, edge cases, \
             and how this fits into the broader system. Produce clear, actionable \
             design documents or code structures.\n\n\
             When done, summarize your design decisions and rationale.",
            id = task.id,
            title = task.title,
            desc = task.description,
        ),
        "review" => format!(
            "You are working on task {id}: {title}\n\n\
             This is a REVIEW task. Analyze the code without making changes.\n\n\
             Description: {desc}\n\n\
             {criteria}{files}\
             Read the relevant code, identify issues, and provide a clear \
             assessment. Do NOT modify files — this is a read-only review.\n\n\
             When done, summarize your findings.",
            id = task.id,
            title = task.title,
            desc = task.description,
        ),
        "test" => format!(
            "You are working on task {id}: {title}\n\n\
             This is a TESTING task. Focus on test coverage and quality.\n\n\
             Description: {desc}\n\n\
             {criteria}{files}\
             Write thorough tests with edge cases. Run existing tests to verify \
             nothing breaks.\n\n\
             When done, summarize what tests you added and their results.",
            id = task.id,
            title = task.title,
            desc = task.description,
        ),
        "document" => format!(
            "You are working on task {id}: {title}\n\n\
             This is a DOCUMENTATION task. Focus on clarity and completeness.\n\n\
             Description: {desc}\n\n\
             {criteria}{files}\
             Write clear, accurate documentation. Include examples where helpful.\n\n\
             When done, summarize what you documented.",
            id = task.id,
            title = task.title,
            desc = task.description,
        ),
        _ => format!(
            "You are working on task {id}: {title}\n\n\
             Description: {desc}\n\n\
             {criteria}{files}\
             Complete this task. When done, summarize what you did.",
            id = task.id,
            title = task.title,
            desc = task.description,
        ),
    }
}
