use super::{ExecutionResult, ToolAdapter};
use crate::core::state::ForgeState;
use crate::core::task::{AgentType, Task};
use std::path::Path;
use std::process::Command;

pub struct CodexAdapter;

impl ToolAdapter for CodexAdapter {
    fn name(&self) -> &str {
        "codex"
    }

    fn render_config(
        &self,
        state: &ForgeState,
        tasks: &[Task],
        project_root: &Path,
    ) -> anyhow::Result<()> {
        let assigned: Vec<_> = tasks
            .iter()
            .filter(|t| t.assigned_to.as_ref().is_some_and(|a| *a == AgentType::Codex))
            .collect();

        let mut content = String::new();
        content.push_str("# AGENTS.md (Auto-generated by Forge Orchestrator)\n\n");
        content.push_str(&format!("**Project:** {}\n", state.project_name));
        content.push_str(&format!(
            "**Last updated:** {}\n\n",
            state.updated_at.format("%Y-%m-%d %H:%M UTC")
        ));
        content.push_str("---\n\n");

        if assigned.is_empty() {
            content.push_str("## Status\n\nNo tasks currently assigned to Codex.\n\n");
        } else {
            content.push_str("## Assigned Tasks\n\n");
            for task in &assigned {
                content.push_str(&format!(
                    "### {}: {}\n\n{}\n\n",
                    task.id, task.title, task.description
                ));
                if !task.acceptance_criteria.is_empty() {
                    content.push_str("**Acceptance Criteria:**\n");
                    for c in &task.acceptance_criteria {
                        content.push_str(&format!("- [ ] {c}\n"));
                    }
                    content.push('\n');
                }
                if !task.locked_files.is_empty() {
                    content.push_str("**Files you may modify:**\n");
                    for file in &task.locked_files {
                        content.push_str(&format!("- `{file}`\n"));
                    }
                    content.push('\n');
                }
            }
        }

        content.push_str("## Rules\n\n");
        content.push_str("- Complete tasks one at a time\n");
        content.push_str("- Do NOT modify files outside your assigned task scope\n");
        content.push_str("- Run tests before marking a task complete\n");
        content.push_str("- Check `.forge/state.json` for current orchestration state\n");

        std::fs::write(project_root.join("AGENTS.md"), content)?;
        Ok(())
    }

    fn execute_headless(
        &self,
        task: &Task,
        project_root: &Path,
    ) -> anyhow::Result<ExecutionResult> {
        let prompt = format!(
            "Complete task {id}: {title}\n\nDescription: {desc}\n\n\
             {criteria}\
             When done, summarize what you did.",
            id = task.id,
            title = task.title,
            desc = task.description,
            criteria = if task.acceptance_criteria.is_empty() {
                String::new()
            } else {
                format!(
                    "Acceptance criteria:\n{}\n\n",
                    task.acceptance_criteria
                        .iter()
                        .map(|c| format!("- {c}"))
                        .collect::<Vec<_>>()
                        .join("\n")
                )
            },
        );

        let output = Command::new("codex")
            .args(["exec", &prompt])
            .current_dir(project_root)
            .output()?;

        let exit_code = output.status.code().unwrap_or(-1);
        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();

        let combined = if stderr.is_empty() {
            stdout
        } else {
            format!("{stdout}\n\nSTDERR:\n{stderr}")
        };

        Ok(ExecutionResult {
            success: output.status.success(),
            output: combined,
            exit_code,
        })
    }
}
